### ISSUE TITLE
change /about/#leadership to /about/#team

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#103]
I had to change https://ropensci.org/about/#leadership to /about/#team in the ropensci-at-meetings posts. Does that need to be updated elsewhere in site (I don't know how to search for that)

**Comment by jeroen** [comment]
@stefaniebutland most text editors have a feature to find or replace in all files. In sublime text it is under `find > find in files` and there you can fill out a 'replace' field.

**Comment by stefaniebutland** [comment]
Woohoo! squashed and merged this fix with above tip
