### ISSUE TITLE
Wow, beautiful! Can we make it easier to scroll through collaborators page?

### ISSUE THREAD

**Issue by cboettig** [ropensci/roweb2#110]
Congrats to everyone on the launch of the new website, it really looks stunning.  

Minor issue here, but I was wondering if there was a way to make the collaborators a bit easier to scroll through? https://ropensci.org/about/#collaborators  The auto-advance is really slick and it's nice to keep seeing new faces along the bottom of a page as an accent to some other content, but it's pretty hard to browse through the current list if you're actually trying to find someone or just get the big picture.  

The old "Community" page was absolutely my favorite page on the website for the nice wall of people it showed.  I do like how we spell out a bit more what we mean by 'collaborator' (though maybe our onboarding editors deserve some higher billing?)  The collaborators display feels a bit more buried  now that it's a footer link and not a top-level menu.  

The new community page is gorgeous!  I really like the background carousel of images behind the 'community calls' panel.  Again super minor, but I was wondering if there was a design adjustment so that reader sees those smiling faces and not just the wall of text when they click on the Community tab?

Maybe a bit late to be making these tweaks, sorry for not chiming in earlier.  Anyway, overall just wanted to say really great job.

**Comment by stefaniebutland** [comment]
@cboettig Thanks for the immediate feedback! For majority of stuff I'm not able to make changes but I'll plus-one your suggestion to have people's beautiful faces appear before a bunch of text (e.g. the carousel currently associated with button that goes to Community Calls).

This launch was meant to be a sort of minimal viable product to finally get the site out there so I hope we can incorporate some of your suggestions in next phase.

**Comment by stefaniebutland** [comment]
@cboettig Karthik and I discussed this briefly and agreed that first we need to fix / clean up functionality of the site as is and we'll take into account changes to collaborators, community etc later when we review design-type things.

**Comment by maelle** [comment]
no collaborators page in the new design
