### ISSUE TITLE
add staff job titles to About

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#120]
Add job titles for staff members under our names https://ropensci.org/about/#team. Important so people can get perspective on team make-up

**Comment by stefaniebutland** [comment]
Should discuss this as part of related issue #84

**Comment by maelle** [comment]
The team part of the about page is already a bit crowded so I think adding titles to it would demand a big re-design.

A partial solution that could emerge once #373 is merged would be to
1. Add bio to the authors metadata of all people listed in the about/ page
2. Link to the author page (even for non staff e.g. leadership? currently only for staff)

E.g. when clicking on your name in the PR as it is now I see your bio @stefaniebutland https://deploy-preview-373--ropensci.netlify.com/authors/stefanie-butland/ that includes your "title".

**Comment by maelle** [comment]
Should we keep this issue open as a reminder for when/if the team part of the about page gets completely redesigned?

**Comment by maelle** [comment]
will be the case in the new design
