### ISSUE TITLE
can't scroll side to side in code blocks 

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb2#126]
on mobile and desktop (though not likely to be a problem on desktop) can't scroll side to side within a code block. is it something we can turn on easily?

**Comment by stefaniebutland** [comment]
I reported this a while back but Jeroen pointed out you can click and scroll. Challenge is, it's really not obvious. Took me a while to re-remember how.

**Comment by sckott** [comment]
okay, fine on desktop, but main problem is mobile, 

@jeroen is there a way to scroll horizontally through code blocks on mobile?

**Comment by sckott** [comment]
this definitely still seems like an issue or is it just me?

**Comment by maelle** [comment]
We even got someone complaining about it https://discuss.ropensci.org/t/where-to-go-observe-birds-in-radolfzell-an-answer-with-r-and-open-data/1295/3
