### ISSUE TITLE
preview no longer working for 3 PRs

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#130]
@jeroen @karthik  requesting help. Preview of pull requests for 3 blog posts no longer working - takes me to Missing page.
- https://github.com/ropensci/roweb2/pull/128
- https://github.com/ropensci/roweb2/pull/127
- https://github.com/ropensci/roweb2/pull/125

This new PR previews as expected: https://github.com/ropensci/roweb2/pull/129
![screen shot 2017-11-12 at 3 20 22 pm](https://user-images.githubusercontent.com/11927811/32877545-e461eea2-ca56-11e7-986a-20284d99ae12.png)

**Comment by jeroen** [comment]
It may be a temporary glitch in netlify. Can you try to push a new commit to #125 and wait for netlify to update and see if it has been fixed?

**Comment by stefaniebutland** [comment]
working now (without me doing anything)
