### ISSUE TITLE
Show icon for RSS feed for blog and technotes somewhere

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb2#143]
e.g., 

https://ropensci.org/blog/index.xml
https://ropensci.org/technotes/index.xml

Tag specific https://ropensci.org/tags/r/index.xml

**Comment by maelle** [comment]
I can add this at the bottom of technotes and blog list pages together with the sentence about the archive and tags pages cf #23 #313

**Comment by sckott** [comment]
sounds good

**Comment by maelle** [comment]
I also need to mention the JSON feed if #315 gets approved by @sckott

**Comment by maelle** [comment]
will be tackled by #320
