### ISSUE TITLE
The line height in li elements is off

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb2#147]
It's smaller than that of a paragraph and that looks off. Also the spacing above and below headings is also quite inconsistent.

**Comment by jeroen** [comment]
Some of this might have been fixed in https://github.com/ropensci/roweb2/commit/b9ee8428804aef310ea01d320492c4cf63b0b1e4

**Comment by maelle** [comment]
What has _not_ been fixed yet?

**Comment by maelle** [comment]
![image](https://user-images.githubusercontent.com/8360597/44804827-d6c46380-abc2-11e8-8a8c-de3931ebc31e.png)
https://ropensci.org/blog/2018/08/28/birds-ocr/
