### ISSUE TITLE
keep record of past events from calendar

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#155]
Is there a way to comment out past events here instead of deleting them?https://github.com/ropensci/roweb2/blob/master/themes/ropensci/static/js/calendarJSON.js

Idea is to have minimal-effort record of past events rOpenSci has participated in, for reports for ex.

Karthik suggested "You can create a new page with a json table called past events and have that linked at the bottom of this table."

**Comment by jeroen** [comment]
So this concerns the calendar showed here, right? https://ropensci.org/community/

**Comment by stefaniebutland** [comment]
Yes

**Comment by maelle** [comment]
At the moment there are 3 issues linked to the calendar #157 #155 #92, I've just added a label for easier browsing.

**Comment by stefaniebutland** [comment]
See summary comment: https://github.com/ropensci/roweb2/issues/92#issuecomment-405694632

**Comment by maelle** [comment]
I understand the need to archive past events but would you need a table of all past events as an archive page on the website? 🤔

**Comment by stefaniebutland** [comment]
> would you need a table of all past events as an archive page on the website?

No, was aiming to keep as internal record of events/talks that we can refer to went writing reports for example

**Comment by maelle** [comment]
Ok, great, then if all old events are archived as Markdown files, one could whip up a script using the `yaml` package, e.g. run it before each report to rectangle the events i.e. go from info in individual files to one big table.

**Comment by maelle** [comment]
And it'd mean I'd consider my calendar work done once I've written an example of such a script.

**Comment by maelle** [comment]
Code to retrieve info about events stored in a private repo.
