### ISSUE TITLE
upcoming events table is very low profile - almost hidden

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#157]
The Upcoming events table shows in two places on our site at the bottom of these pages
- https://ropensci.org/
- https://ropensci.org/community/
however there is no direct link to either of these, and no spot in the website footer for it. We try to duplicate this information in our public rOpenSci Google calendar (I think directly embedding it did not work)

The Upcoming events table on our site can be valuable to show people not only rOpenSci events, but conferences and presentations around the world that staff and leadership are participating in. Shows people what conferences we value and gives them an opportunity to meet with us where they are.

Solutions?
- add an anchor so we can refer directly to the calendar with a URL (rather than saying "at the bottom of this page...")?
- add link in the website footer. But would need to remove another footer element to make room - is that justified?
- figure out how to embed the Google calendar directly in our site to avoid having to post in two places

**Comment by maelle** [comment]
At the moment there are 3 issues linked to the calendar #157 #155 #92, I've just added a label for easier browsing.

**Comment by stefaniebutland** [comment]
See https://github.com/ropensci/roweb2/issues/92#issuecomment-405694632

**Comment by maelle** [comment]
If we create the calendar feed, it'd have an URL (and yep one can add an anchor to the calendar html version on the community page I think)

**Comment by maelle** [comment]
> add link in the website footer. But would need to remove another footer element to make room - is that justified?

In my opinion a calendar icon near the GitHub, Twitter and Vimeo icons, pointing to events/, would be fine.

**Comment by maelle** [comment]
cf #358
