### ISSUE TITLE
Add note to packages page about JS blocking

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb2#161]
for https://ropensci.org/packages/ we should maybe add a note somewhere to notify users that if the table doesn't show up they may need to turn off JS blocking  - or are there other reasons the table wouldn't show up? @jeroen ?

**Comment by jeroen** [comment]
Have we gotten complaints about this? JS blocking is pretty unusual. Almost no website these days works without JS so users that block JS will probably know what's the problem.

**Comment by maelle** [comment]
Should this be closed?

**Comment by jeroen** [comment]
Yes this is silly.
