### ISSUE TITLE
bullet CSS

### ISSUE THREAD

**Issue by noamross** [ropensci/roweb2#172]
Something is odd with display of list items on the blog.  The bullets show up at the _last_ line of a list item (example below).  As far as I can tell, this has something to do with the fact that list items are wrapped in `<li><p>Text</p></li>` rather than just  `<li>Text</li>`.  Not sure if that means the CSS should change, or the way the markdown compiles should change, or something else.

<img width="865" alt="screenshot 2018-04-11 10 45 44" src="https://user-images.githubusercontent.com/571752/38633915-e33970f8-3d75-11e8-804c-4054eacdaa9b.png">

(from https://ropensci.org/blog/2018/03/16/thanking-reviewers-in-metadata/)

**Comment by maelle** [comment]
This bug annoys me more and more. I'm trying to understand how to improve this.

I've had a look at the search results of https://github.com/ropensci/roweb2/search?q=list-style&unscoped_q=list-style and am not too sure where the problem happens.

I've looked at https://www.w3schools.com/css/css_list.asp and am wondering whether the problem could be "solved" by adding `list-style-position: inside;` but I don't know in which pcss/css file. Any clue @jeroen? If not, I'll just experiment until it works. 😀

**Comment by maelle** [comment]
It's probably due to `ul` and `ol` properties defined in the new style, like for superscripts cf #132

**Comment by maelle** [comment]
Notes

`ul` (and `ol`) present in

*  reset.pcss https://github.com/ropensci/roweb2/blob/master/themes/ropensci/static/css/reset.pcss

* typesetting.pcss https://github.com/ropensci/roweb2/blob/master/themes/ropensci/static/css/scroller.pcss

**Comment by maelle** [comment]
I really don't see where the paragraph inside line style is defined.

**Comment by maelle** [comment]
Although I see that view-source:https://ropensci.org/community/ also has p inside li elements of lists, but it looks good (but is not generated from Markdown)

**Comment by maelle** [comment]
Or maybe, as noted by @noamross at the very beginning of this issue, the problem is within the Markdown generating process, so am looking at Blackfriday docs again.
