### ISSUE TITLE
Blog post templates

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#181]
Should the README have a link to actual blog post md and Rmd templates? With blank topic id, and proper header format.

I had started working on templates in `rodev` cf https://github.com/ropenscilabs/rodev/blob/master/inst/templates/post_template.Rmd but they don't have blank topic and don't show one should use "###" for the Section headers.

Cc @stefaniebutland

**Comment by maelle** [comment]
I'd be happy for the templates to live in this repo and to be downloaded by `rodev` by the way.

**Comment by stefaniebutland** [comment]
Templates for blog post and tech notes and linked from README would be very helpful. Would prevent lots of questions!

**Comment by maelle** [comment]
Should I put the templates here or link to https://github.com/ropenscilabs/roblog ? (yes a very new very WIP :sparkles: helper package for roweb2 blogging :sparkles:)
