### ISSUE TITLE
Add unconf18 etc tags

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#194]
Instead of having only the "unconf" tag, have both "unconf" and "unconf-YY" tags? What do you think @stefaniebutland?

**Comment by stefaniebutland** [comment]
agreed.
Example1:
- unconf
- unconf18

Example2:
- unconf
- ozunconf17

**Comment by maelle** [comment]
We might even be more efficient with some sort of google sheets.  Each row = a post. Then columns?? In any case the idea would then be to use the sheet to add all tags at once using the yaml package. This instead of opening each post.

**Comment by maelle** [comment]
The sheet would be pre filled with current tags.

**Comment by maelle** [comment]
Each tag = 1 column.

Would such a workflow make sense @stefaniebutland?

**Comment by stefaniebutland** [comment]
sounds good. I know Scott has grabbed all tags for each post in past so part of that code is done

**Comment by stefaniebutland** [comment]
I did want to update other blog post tags but didn't get to point of deciding what tags were best. We can either just update the unconf ones now, or discuss (slack call incl Scott too) how best to tag posts

**Comment by maelle** [comment]
Well with that googlesheets workflow you can more easily add any tag in the future. Will look into it next week

**Comment by maelle** [comment]
I want post tag adding to be as easy as GitHub repo topic adding

**Comment by maelle** [comment]
It'd be launched by a function. Then the shiny app would need the local path to content/. Then there'd be an editable table pre-filled with yaml info. Then each time one would click on save it would edit the posts and re-load the table. When one is done one would commit and push (in a branch)

The tricky part will be to make the "table of some sort" user friendly (with a column per tag it risks being very wide)

**Comment by maelle** [comment]
https://github.com/jrowen/rhandsontable

**Comment by maelle** [comment]
The app should also allow creating new tags that have never been used yet.

**Comment by maelle** [comment]
WIP https://github.com/ropenscilabs/blogyaml

**Comment by maelle** [comment]
Assigning myself until I have a good app to show you @stefaniebutland

**Comment by maelle** [comment]
Now there's an app to use for this 😺

**Comment by stefaniebutland** [comment]
https://github.com/ropenscilabs/blogyaml works like a charm. Tags added to all (I think) unconf blog posts: unconf, unconf14, unconf17, unconf18, ozunconf, ozunconf16, ozunconf17
