### ISSUE TITLE
Plural vs singular in tags

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#199]
E.g. packages vs package, databases vs database, meetings vs meeting.

Not entirely sure I see the need for this, but I haven't looked closely at corresponding blog posts.

**Comment by stefaniebutland** [comment]
I agree we should keep one form of each. 
And we should probably add guidance to https://github.com/ropensci/roweb2#blog-post-editorial-suggestions

**Comment by sckott** [comment]
yes, one of each sounds good
