### ISSUE TITLE
Automatically generate packages page from manifest

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb2#2]
Jeroen said he can figure this out

**Comment by maelle** [comment]
A few months later 😉 The currently produced big codemeta.json of all packages has keywords, derived from GitHub repo topics (and from keywords in DESCRIPTION for the only package that has them :grin: ). 

* I need to add more GitHub repo topics over both organizations, and also more status badges.

* I'll soon write code to actually process the big codemeta.json into a table. That table will have status badges.

* The codemeta creating and processing should run automatically, currently in the future.

* The packages page should have search across package names, description and keywords. I'll try to think about this too.

**Comment by maelle** [comment]
Also noting https://github.com/ropensci/roweb2/issues/56

**Comment by jeroen** [comment]
We should discuss in the meeting what the plan is exactly. Should this replace @sckott https://github.com/ropensci/roregistry?

**Comment by sckott** [comment]
Yes we should discuss. Yes, the plan is to generate packages page from this metadata, but it shouldn't be too different from how you have it setup now in that we'll run a cron job to generate the single json file and you can pull that in as you do know

**Comment by jeroen** [comment]
Meeting update: once maelle has implemented the code that adds the keywords to the registery, we want to show those in the front-end table.

**Comment by maelle** [comment]
Another note, I'd like to auto-generate the different filters https://github.com/ropensci/roweb2/blob/master/content/packages.html#L31 based on the categories present in the registry csv (this way if we update categories, no need to update the website table code).

**Comment by maelle** [comment]
There's also some "manual" category grouping at the moment https://github.com/ropensci/roweb2/blob/3d3c0f0c598459f0e5ca5b1bafbd1c3edcb58bde/themes/ropensci/static/js/tableinit.js#L35 (not criticism, just a note I'm making)

**Comment by maelle** [comment]
I need to figure out whether it'd be problematic to use a csv instead of a JSON as input.

**Comment by maelle** [comment]
Or I can also produce a csv, might be easier 🤷‍♀️

**Comment by maelle** [comment]
In the current table on the site the maintainers names look like hyperlinks but they aren't. I wonder whether there should be... a mailto:? A view filtered by maintainer?

**Comment by karthik** [comment]
Ideally it should go to their GitHub profile page.

**Comment by karthik** [comment]
or actually i prefer a filtered view by maintainer

**Comment by maelle** [comment]
good idea by @noamross, the table should also show which packages have been reviewed.

**Comment by maelle** [comment]
> or actually i prefer a filtered view by maintainer

I had missed that it's already implemented actually!

**Comment by sckott** [comment]
cron job is running now 

I still need to sort out adding new repos as they are added to ropensci/ropenscilabs

**Comment by maelle** [comment]
Yay!

So there is no API call to GitHub before cloning at the moment?

**Comment by sckott** [comment]
i think this is all set now @maelle

**Comment by maelle** [comment]
or at least we now track remaining issues elsewhere 😁 https://github.com/ropenscilabs/makeregistry
