### ISSUE TITLE
Line breaks in blog posts are not parsing

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb2#20]
New blog: https://new.ropensci.org/blog/2017/06/09/unconf17recap5/
old blog: https://ropensci.org/blog/blog/2017/06/09/unconf_recap_5.html

This must be a Hugo issue.

**Comment by maelle** [comment]
I see this in unconf recaps too (GitHub link should be on a new line but isn't) :sob: cc @stefaniebutland in case you notice this in my recaps.

**Comment by maelle** [comment]
Play with the "inline-spacing" (I already forgot the name @jeroen) rule to see whether it fixes this and what it breaks.

Note to self: Chrome tools.
