### ISSUE TITLE
Talks in resources page

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#221]
There are some slidedecks under "talks" in https://ropensci.org/resources/

* Should there be an effort to always add slidedecks or links to them there? By staff and anyone giving a talk about rOpenSci (onboarding editors and other "ambassadors")? If so, how should the workflow look like?

* Should https://github.com/ropensci/talks be deleted once https://github.com/ropensci/talks/tree/master/yvr-2018 has been moved to a more general place?

I added the "calendar" label to this issue because slidedecks might be linked from the historical calendar mentioned in #155 by @stefaniebutland.

**Comment by stefaniebutland** [comment]
Given the large number of meetings rOpenSci people speak at, I don't think it is worthwhile having a policy of always adding links to slide decks there. We *could* aim to keep examples of different types of talks e.g. general rOpenSci, software review, taxonomy suite.

I agree this is intimately linked with the calendar issues

**Comment by maelle** [comment]
Whilst tackling this one day, the resources page could be transformed to Markdown like the other pages I've worked on in #293

**Comment by maelle** [comment]
If we go with my proposal in #316 then a YAML field of event could be slides, that'd be an URL to the slide when available, and that'd be used in the template for single event pages.

**Comment by maelle** [comment]
in the new design slidedecks to be stored as resources in the YAML of events
