### ISSUE TITLE
Resources for package users?

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#223]
Now the dev_guide has a chapter for new contributors, should the community page also include some resources for _users_? 

It could include

- how to explore the packages suite
- how to ask for help, writing up @sckott's talk from a comm call https://scotttalks.info/qropensci/
- how to report use cases

Thoughts? Cc @stefaniebutland

**Comment by maelle** [comment]
And there could be some sort of text about how users can be contributors

**Comment by stefaniebutland** [comment]
Some of this seems to fit in the [Contributing Guide](https://ropensci.github.io/dev_guide/contributingguide.html) itself because of the continuum from users to contributors e.g. reporting use cases. The community page could include some info for users and point to the guide

**Comment by maelle** [comment]
The current phrasing "read our Contributing Guide to learn how you can contribute to rOpenSci as a user or developer." fix this issue.
