### ISSUE TITLE
Can't search in table of packages

### ISSUE THREAD

**Issue by privefl** [ropensci/roweb2#227]
At https://ropensci.org/packages/, 
The table remains "Loading...".
When I check anything in FILTERS, the message becomes "No data available in table".

I'm using Mozilla Firefox for Linux Mint (Version 60.0.2 - 64 bits).

**Comment by maelle** [comment]
Thanks for the bug report @privefl!

@jeroen is it something you have observed in the past?

The table works for me at the moment.

**Comment by sckott** [comment]
@privefl you could open firefox inspector and see if any errors are being thrown there

**Comment by jeroen** [comment]
@privefl are you using any adblockers or privacy badger that may block the external data source?

**Comment by privefl** [comment]
I'm using Adblock indeed. Disabling it fixes this issue.
