### ISSUE TITLE
Comm calls

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#228]
Opening this here because I don't dare messing with https://github.com/ropensci/commcalls issue tracker

* I like the landing page but would sometimes like to link to one call in particular so could we add anchors in the table?

* I don't think there's a clear link from the website, the paragraph in community doesn't reflect the fact that one can use resources from former comm calls.

**Comment by sckott** [comment]
+1 on adding anchors

**Comment by maelle** [comment]
Am experimenting

**Comment by maelle** [comment]
Okay so I'm ready to change it back if it's too messy @stefaniebutland but here is what I've done:

* I've converted the Markdown table to an html table (by copy-pasting the source of the rendered version 🙈 ). I think it's not much harder to edit than the raw Markdown table, but maybe it is, in which case this is all a very bad idea. 

* I've added anchors for http://communitycalls.ropensci.org/#past-calls (`<a name="next-call">[Next Call](#next-call)`) where `<a blabla>` is the anchor and `[Next Call](#next-call)` is the Markdown syntax for adding this link. It works both in the GitHub README, https://github.com/ropensci/commcalls#next-call (there was already an automatic anchor for the header, but not in the website) and in the website http://communitycalls.ropensci.org/#next-call

* I've added two anchors in the table. Example

```
 <tr id = "2018-01-30">
      <td><a href="#2018-01-30">2018-01-30</a></td>
```

So I add an id to the raw and then the date in the first cell contains a link to that anchor id. In the README it gives you https://github.com/ropensci/commcalls#2018-01-30 and in the website http://communitycalls.ropensci.org/#2018-01-30

If you think it can work for you @stefaniebutland then I can add all the anchors to the rest of the rows (unless you want to do it) and if it doesn't work for you then I'll change it all back. 👼

**Comment by stefaniebutland** [comment]
not ignoring this @maelle but not looking at it just yet. Thank you!

**Comment by stefaniebutland** [comment]
Thanks @maelle. Easy to edit. Added anchors so we can link directly when the urge strikes
