### ISSUE TITLE
add author names to Tech Notes list?

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#229]
Since these are written by both staff and sometimes authors of onboarded software, I'd bet people would like to see their name beside the technote title in this list: https://ropensci.org/technotes/

**Comment by sckott** [comment]
yeah, probably, thoughts @jeroen (he designed this page)

**Comment by maelle** [comment]
I'll try something after #293 is merged.

**Comment by jeroen** [comment]
I kept it minimal on purpose but if people prefer to have names in the list that's OK too.

**Comment by maelle** [comment]
Don't worry I'll request a review to be sure the new version complies with Dutch design 😁
