### ISSUE TITLE
link to /tags page from Blog page?

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb2#23]
no link right now - should we add one ?

**Comment by maelle** [comment]
* Tags are indicated for each post but at the bottom of the page. I prefer tags at the top. #226

* There is a tags page but it is not linked from anywhere yet, right? Where should it be linked from?

* What would be the difference between an archive page and browsing the different pages of https://ropensci.org/blog/ ?

**Comment by stefaniebutland** [comment]
my impression is that archive page would have all posts in a single page (so you can search by ctrl-f, which I want to do VERY often, but can't) rather than having to click through diff pages of https://ropensci.org/blog/

**Comment by sckott** [comment]
right on archive page @stefaniebutland

**Comment by maelle** [comment]
Ah right! Super useful! I have one on my own website 😁

**Comment by maelle** [comment]
For info in #293 I'll tinker with the tags page (which is html at the moment, I'm getting rid of html under content)

**Comment by maelle** [comment]
@sckott From my PR: https://deploy-preview-293--ropensci.netlify.com/tags/ I've created a template for this page, "terms.html". Your "tags.html" under content/ isn't used at all actually, Hugo uses"list.html" from default/, which is the list template for the blog so it looks a bit weird http://ropensci.org/tags (I'm learning a ton about Hugo lookup order for templates :wink: )

**Comment by maelle** [comment]
Regarding _where_ to add a link to the archives and tags pages, not sure where to do that. @stefaniebutland , where were you imagining them? Maybe at the bottom of each blog/technotes page, i.e. at the bottom of https://ropensci.org/blog/, https://ropensci.org/blog/page/2/ etc. "Find all our blog posts and tech notes by date _here_ and by tag _here_" pointing to ropensci.org/tags (that exists) and to ropensci.org/archive (that doesn't exist yet).

**Comment by maelle** [comment]
I made https://deploy-preview-293--ropensci.netlify.com/tags/ _very_ compact, it looks better than say https://masalmon.eu/tags/ but I find it a bit ugly, I welcome any suggestion. 

I think it's not a good idea to have posts grouped by tag under each tag name in https://deploy-preview-293--ropensci.netlify.com/tags/  because it would make it difficult to get an overview, and when clicking on each tag, one gets a list similar to the blog, https://deploy-preview-293--ropensci.netlify.com/tags/community/

**Comment by maelle** [comment]
@stefaniebutland said one archive page for both blogs is best, I agree, I'll try to get that to work.

Once both the archive and tags pages are up, I'll complement the list.html templates of blog/ and technotes/ with a sentence for the bottom of each page "Find all posts blabla".

**Comment by maelle** [comment]
@sckott I stole the issue from you, sorry :wink: 🙏

**Comment by sckott** [comment]
no problem at all!
