### ISSUE TITLE
On the blog page the title of tech notes are all lower-case

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#269]
![image](https://user-images.githubusercontent.com/8360597/45077138-b0378880-b0ec-11e8-9eba-0454b91ce31f.png)

was it a design choice @jeroen? if not I can try changing that.

**Comment by jeroen** [comment]
Hmm I don't think that was a deliberate design choice.

**Comment by maelle** [comment]
Ok then I'll investigate when I get a chance 🕵️‍♀️

**Comment by jeroen** [comment]
Ah maybe it actually was a choice: https://github.com/ropensci/roweb2/blob/716d82e7fcf22dfe7f833e52e0a67ff9e4845255/themes/ropensci/static/css/table.pcss#L53

**Comment by maelle** [comment]
Ok. I think it should be changed, but we can vote. 😉

**Comment by jeroen** [comment]
OK you can open a PR. I thought the mixed case titles made it look a bit messy. But I don't feel very strongly.
