### ISSUE TITLE
GDPR config?

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#272]
See https://github.com/tidyverse/tidyverse.org/issues/197

**Comment by sckott** [comment]
@maelle in the agenda for the staff call you asked about a twitter thing? Looks like there's some settings in the GDPR hugo configuration. What exactly are you asking about?

**Comment by maelle** [comment]
Twitter was an example of a choice to be made, sorry. In https://gohugo.io/about/hugo-and-gdpr/ you can see all the parameters to choose.

**Comment by maelle** [comment]
E.g. my own config is https://github.com/maelle/simplymaelle/blob/master/config.toml#L102 (my website doesn't have Google Analytics enabled which will be a difference)

**Comment by sckott** [comment]
I would think the same as your config except a few things:

- googleanalytics: enable
- instagram: have we had any instagram embeds? I don't think we've had any

**Comment by maelle** [comment]
I don't have any instagram embedded either, it is just in case 😂

**Comment by maelle** [comment]
related PRs

- [ ] #476 
- [ ] #477 
- [ ] #478 
- [ ] #479

**Comment by maelle** [comment]
@sckott assigning you because the last related PR is about Disqus, and I think it won't be merged before my leave.

**Comment by sckott** [comment]
ok
