### ISSUE TITLE
Blog Dates and Hugo

### ISSUE THREAD

**Issue by rtaph** [ropensci/roweb2#285]
@stefaniebutland,

What do you think about adding a sentence to the README to explain that post-dated blog entries do not appear in the served content through hugo? This took me a while to figure out, and I think new users could benefit from this insight if they are writing blogs for future publication.

**Comment by stefaniebutland** [comment]
Ah sorry about that @rtaph. Are you referring to trying to render your post locally, here in the README https://github.com/ropensci/roweb2#installing-hugo-for-local-preview?

I think `hugo serve -F` is needed for rendering post-dated blog entries locally. If this is what you're referring to I'll update the README.

Thank you for letting us know

**Comment by rtaph** [comment]
Yes, brilliant. I was having trouble with my local hugo instance, and did not know about the `-F` flag.
