### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by jeroen** [ropensci/roweb2#30]
Part of the reason that our headers in the blog are huge is that the designer was using `<h3>` and `<h4>` html headers in her [design](https://github.com/rosadmin/website_branding/blob/master/rOpenSci-website/blog_single.html#L42) however we use `## blabla` in our markdown which get rendered into `<h2>` headers.

Perhaps there way to make hugo convert our `## subsection` markdown titles into `<h3>`?

**Comment by maelle** [comment]
Other header problem, I used `####` in https://deploy-preview-177--ropensci.netlify.com/blog/2018/04/26/rectangling-onboarding/ and see the long one "Digesting them and complementing them with Airtable data" looks bad because of the line break cc @stefaniebutland

**Comment by maelle** [comment]
@jeroen would this only require changing https://github.com/ropensci/roweb2/blob/master/themes/ropensci/static/css/blog.pcss? If so, I can implement this change. 

I just wonder if it can be problematic for posts that'd have used h1, h2 _and_ h3, because with your suggestion h3 and h1 would have the same size. Not sure any post does that though (I can look another time).

**Comment by maelle** [comment]
https://github.com/sourcey/moxygen

**Comment by maelle** [comment]
@jeroen I've just had a look at the use of heading levels over all posts cf https://gist.github.com/maelle/85d10b4f793dc76f44ecd6a8522e2e7f

Some posts use only level 2, others only levels 3. The maximum number of levels by post is 3 (1,2,3 / 2,3,4)... If there's a way to write XML back to Markdown I'd like to homogenize the use of levels over all posts and all tech notes if needed using `xml2::xml_set_attr`.

**Comment by maelle** [comment]
Here's how I'd update headers https://gist.github.com/maelle/8c4316286c686519911cdce24ea9fa83

Missing is the step writing the XML back to Markdown (and also a step to re-add the YAML and then save the resulting file).
