### ISSUE TITLE
Tweak RSS templates

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#335]
As requested by @jeroen 

* Use Hugo default RSS feed for all pages

* Create an aggregate RSS feed for blog+tech notes, using the current custom RSS feed template (which include full content and a cover image).

* Then submit that aggregate RSS feed to R-Bloggers.

Jeroen, note that the JSON feed is full content IIRC.

**Comment by jeroen** [comment]
Instead of submitting to rbloggers we can first update the redirect: https://github.com/ropensci/roweb2/blob/master/public/_redirects#L6

**Comment by maelle** [comment]
that's a good idea
