### ISSUE TITLE
Make the R-bloggers RSS feed suffix-less

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#338]
I.e. getting the result of https://github.com/ropensci/roweb2/commit/d495668d2d484233f1c2370f49fdf2392318d769 without the redirect.

Potentially useful forum threads I found
* https://discourse.gohugo.io/t/solved-eliminate-xml-suffix-custom-rss-uri/7532/9
* https://discourse.gohugo.io/t/how-can-i-change-the-rss-url/118

Apparently if you edit the suffix you'll have to rename the RSS custom template?

Have fun! 😸

**Comment by maelle** [comment]
@jeroen can we close this or do you still home to solve this?

**Comment by jeroen** [comment]
I don't remember what this was about. But our r-bloggers feed works?

**Comment by maelle** [comment]
it works, you were just annoyed it has a suffix :joy: 

It also works on the new website https://roweb3-hugo.netlify.app/rbloggers/index.xml
