### ISSUE TITLE
Error embedding discourse in a commcall

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#348]
In this commcall @maelle https://raw.githubusercontent.com/ropensci/roweb2/master/content/commcalls/2018-10-16.md, presence of `topicid` for linking discourse thread results in error in preview https://ropensci.org/commcalls/2018-10-16/

"Error Embedding

Referer:https://ropensci.org/commcalls/2018-10-16/

The referer did not match any of the following hosts:

ropensci.org/blog/*
ropensci.org/technotes/*
[Configure Embedding](https://discuss.ropensci.org/admin/customize/embedding)"

Maybe we can do without having comments thread below these comm call pages and I can add under Resources. That would mean omitting `topicid`

**Comment by maelle** [comment]
Oooh I think that maybe forum admin @sckott can fix. 

@sckott I naively thought we could embed discuss threads in comm calls pages like we do for the blog and tech notes. So in the template I copied the same html. But apparently there's an option to change on Discourse side?

Besides, @sckott , do you think it's a technical problem if sometimes we embed the same Discourse thread in a blog post and in a comm call page? (where the blog post is the promotional/summary blog post of the comm call).

**Comment by sckott** [comment]
✅ works now

**Comment by maelle** [comment]
Yay! Thank you!
