### ISSUE TITLE
Add tags to comm calls

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#349]
Using `blogyaml` maybe?

To make them more easily discoverable.

**Comment by stefaniebutland** [comment]
`blogyaml` working thank you! added some tags e.g. `community-call` to all; need to add more

**Comment by maelle** [comment]
Even more or are you happy with your current tagging?

**Comment by stefaniebutland** [comment]
will add more

**Comment by stefaniebutland** [comment]
Added tags to all calls. Now want to remove "community" tag from all comm calls using blogyaml pkg

**Comment by stefaniebutland** [comment]
done in https://github.com/ropensci/roweb2/pull/600
