### ISSUE TITLE
Rename the onboarding tag

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#350]
@stefaniebutland we're in the process of renaming onboarding "software peer-review". So the onboarding tag could be renamed "software-peer-review".

* What's the current difference between the "review" and "onboarding" tag? I think it's the author of the post?

* When changing the tags I'll make sure to also correct links to https://ropensci.org/tags/onboarding/

**Comment by stefaniebutland** [comment]
I'm ok with having only "software peer-review" tag and removing "review" and "onboarding". I've updated the tags recommendation in https://github.com/ropensci/roweb2#blog-post-editorial-suggestions

I think I kept both review and onboarding cause some posts had one and some had another so I 😜 added both tags to ~all
