### ISSUE TITLE
Make date appear on Comm Calls Next Call

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#351]
Date does not appear here
https://ropensci.org/commcalls/

Though the info is present: https://raw.githubusercontent.com/ropensci/roweb2/master/content/commcalls/2018-12-18.md

**Comment by maelle** [comment]
🙀 working on it now (whyyy did I remove it at some point?!)

**Comment by maelle** [comment]
Done but please check it's the right time @stefaniebutland before closing this
