### ISSUE TITLE
Tutorials options

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb2#362]
I think everyone agrees we need to do something about the tutorials on our site. What that is though is not so clear. Here's some options

- keep tutorials as stylized html pages, BUT figure out a way to automate their creation and IMPORTANTLY their updates to the most recent version of the package
- remove html-ized tutorials and instead link out to whatever is the best place to get started for each package. there's various ways to do this, possibly combination of:
    - script that uses some logic for getting the best docs page
    - leverage manually curated newsletter metadata https://github.com/ropensci/biweekly/blob/gh-pages/data/pkg_metadata.csv 
    - script should test that each link at the very least resolves - maybe check somehow that the content is useful?
- any other options to mention here?

**Comment by maelle** [comment]
* not having tutorials and instead having pkgdown pages for all packages and linking to them?

**Comment by sckott** [comment]
I think the idea was that @jeroen could create a pkgdown ropensci template that we could use - do you think that's still worth doing?

**Comment by stefaniebutland** [comment]
> do you think that's still worth doing?

If that's what was decided then definitely yes. Without taking more time, I have a hard time visualizing the technical side of this so I don't have an opinion to share. Just wanted to share those notes from staff mtg. Impostering hard over here

**Comment by sckott** [comment]
sorry, was asking @jeroen if he still wanted to do it

**Comment by maelle** [comment]
in the new design, no tutorials page at the moment.
