### ISSUE TITLE
Update guidance for blog post authors

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#376]
A new screenshot of YAML for a post, and of authors YAML, is needed.

I'm sorry to make you update this again in a short time @stefaniebutland but after that there should be no change in the short/medium term. :pray:

**Comment by stefaniebutland** [comment]
done :-)

**Comment by stefaniebutland** [comment]
good point - I had thought of doing it myself, but it is indeed better for author to choose the links they want to show. Will do

**Comment by stefaniebutland** [comment]
I'm going to use Kelly O'Briant's as example (e.g. woman community member with multiple contributions) once this issue is addressed https://github.com/ropensci/roweb2/issues/383#issue-397097870

**Comment by maelle** [comment]
Is your decision to choose her as an example independent from Scott's choice in the newsletter? If so, it's funny. :smile_cat:

**Comment by maelle** [comment]
I added suggestions to the guidance.

**Comment by maelle** [comment]
So cool  😁 poke @sckott

**Comment by sckott** [comment]
i think i picked her cause she was the lady with the most posts that wasn't staff

**Comment by stefaniebutland** [comment]
Exactly!! Great when we're all doing stuff with some of the same values in mind

**Comment by stefaniebutland** [comment]
done
