### ISSUE TITLE
one or more? authors' pages have no content listed 

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#383]
In updating guidelines https://github.com/ropensci/roweb2/issues/376 I noticed that Kelly O'Briant's page has no content listed despite checking that `authors` in blog YAML looked correct.
- rprofile series: 
  - in https://raw.githubusercontent.com/ropensci/roweb2/master/content/blog/2018-02-09-rprofile-julia-stewart-lowndes.md
  - https://ropensci.org/blog/2018/06/08/rprofile-julia-silge/

At first I thought others were missing too but recalled that there would be no "Find more content by.." for authors of a single piece of content.

**Comment by maelle** [comment]
Which other ones havs this issue?

**Comment by maelle** [comment]
It is orobably the same issue as with Rich and Miles, I'll rename the metadata folder (something wrong with O')

**Comment by maelle** [comment]
Please tell me if you notice any other problem.

It's an issue that's totally puzzling to me because even before I fixed it, the author page of Kelly was fine, only the bottom of her posts was not (and it was the same with Rich). Not sure why Hugo could find the author metadata in one case.
