### ISSUE TITLE
Old authors format for events

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#385]
@stefaniebutland as you might have noticed the authors format in events Markdown file has not changed. I.e. even for staff members the Twitter username needs to be listed.

The reason for that is that I was imagining the case when the attendee is someone external to rOpenSci who has never written a post. If we created an author page for that person, it'd have no content. 

Is it fine or would you prefer them to have such an empty page?

**Comment by stefaniebutland** [comment]
That's a tough question.
- "Content by...[author]" would indeed  look odd with no content
- but it would be quite rare that we're listing a talk/event from a person who is not listed on authors page e.g. Melanie Frazier only participated in a community call but she has an author page
- it does feel odd to use the old author format for an event

Can you think of specific examples where someone would be listed on event and have empty author page? 

I'm thinking having empty author page for rare cases may be ok.

**Comment by maelle** [comment]
Yes, Julia Gustavsen who gave a talk about rOpenSci.

But if you think it is fine to have no content then we could switch!

**Comment by stefaniebutland** [comment]
What's your honest opinion @maelle ?

**Comment by maelle** [comment]
No opinion! For real! Which does not help I know.

**Comment by stefaniebutland** [comment]
In that case, I think it makes sense to use a consistent authors format in our site, and in rare cases a person will have an empty author page.
