### ISSUE TITLE
page title missing from indiv Authors

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#389]
e.g. https://ropensci.org/authors/nicholas-tierney/

![screen shot 2019-01-08 at 5 37 28 pm](https://user-images.githubusercontent.com/11927811/50944221-65d06a80-1444-11e9-8795-cd92a2897f49.png)

Authors list page is ok https://ropensci.org/authors/

**Comment by maelle** [comment]
I'll tackle that at the same time as #381 

The easiest solution will be to rename the `name` parameter in all authors' _index.md `title`. I'll also update the corresponding templates. When I do that the guidance for authors will need to be updated :see_no_evil: 

By the way the authors individual pages don't have a `description` so the Twitter card will be empty. Unless I find a way to set a page variable from the template... I'll explore all that next week.

**Comment by maelle** [comment]
https://discourse.gohugo.io/t/how-to-set-the-description-parameter-of-a-page-from-a-template/16291

**Comment by maelle** [comment]
@stefaniebutland I ended up adapting the head.html partial.

This change fixed the issue you mentioned and also made Twitter cards for authors pages a bit more informative. Try it out via https://cards-dev.twitter.com/validator :-)
