### ISSUE TITLE
Should the tag pages use the archive partial?

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#397]
A question for you @stefaniebutland 

At the moments nearly all lists of posts (by date, by author) use the archive partial which means it's just a list of titles and authors and you see all of them at a glance.

Meanwhile, tag pages e.g. https://ropensci.org/tags/software-peer-review/ have a layout that's more similar to the blog and you can't see all posts at once, you need to click through.

I tend to think tag pages should feature a list similar to the list of content by author. What's your opinion @stefaniebutland? (And anyone reading this who has an opinion is welcome to share it!)

**Comment by maelle** [comment]
(and it'd be an easy change :slightly_smiling_face: )

**Comment by stefaniebutland** [comment]
If I understand correctly, you are suggesting that a tag page like  https://ropensci.org/tags/software-peer-review/ should look more like https://ropensci.org/archive/.

I agree that it is much better to see whole list at a glance, rather than having to click through. So yes please!
