### ISSUE TITLE
Contact form needs a submitter

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb2#4]
Does anyone know of a script/service that can send mail from the form? Right now the form is just a template and does not go anywhere. I could replace this with a typeform iframe as we have on our current website.

**Comment by karthik** [comment]
We need to kill the form ASAP. It doesn’t send us the message and people are just talking into a void.

**Comment by jeroen** [comment]
Let met try to make it work with netlify forms. One sec.

**Comment by jeroen** [comment]
OK that works. https://github.com/ropensci/roweb2/commit/5e8803c5b13494abbd94e099c3b9e6fac21fef36 changes it to netlify native form submissions and we get a notification in slack and email. See https://app.netlify.com/sites/ropensci/settings/forms

**Comment by jeroen** [comment]
Ugh reverted it. Somehow we are not seeing the textarea field even though it is posted for sure.
