### ISSUE TITLE
List future events on fancy author pages?

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#406]
Related to #402 

Should the new design include something about future events listed in our calendar that involve this person and if so, where in the page layout?

@stefaniebutland @jeroen

**Comment by maelle** [comment]
Technically, I suppose it'd be some double `where` on all site pages (to extract events and comm calls with a first where, and in a second look for those with the person name in the attendee or author list).

**Comment by stefaniebutland** [comment]
It's a generous idea, but I feel like displaying future events for an author doesn't add very much value because it would be there for a short time and I don't imagine a person clicking on an author would pay much attention to that.
