### ISSUE TITLE
Comm Call entry shows duplicate description

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#426]
Making comm call entry. Preview shows the description showing up in 2 places. https://deploy-preview-425--ropensci.netlify.com/commcalls/2019-03-27/

Maëlle said "I think I see the issue in the layout file"

**Comment by maelle** [comment]
Fixed in https://github.com/ropensci/roweb2/commit/6ee1a4d2c86de08c3e74c39c2c06916b26167cd3 but you won't see the fix in your PR preview unless you rebase your PR, which I'm not sure is worth the bother since things will look ok after PR (I checked with a local example).

**Comment by stefaniebutland** [comment]
Thank you!
