### ISSUE TITLE
Author page not linked to author Laura DeCicco

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#439]
I can't find the error that leads to Laura DeCicco's author page https://github.com/ropensci/roweb2/blob/master/content/authors/laura-de-cicco/_index.md

not listing this post on which she is an author https://ropensci.org/blog/2017/06/20/checkers/

**Comment by stefaniebutland** [comment]
found the problem. fixing

**Comment by maelle** [comment]
Good catch! I've fixed the issue by renaming the folder. We'll need to make sure there's no similar issue with similar names (i.e. names with a capital letter in the middle).

**Comment by stefaniebutland** [comment]
Thank you @maelle - I was tempted to try that folder rename to fix but didn't know if there would be unanticipated effects
