### ISSUE TITLE
contrast in the footer image

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#451]
Not sure it's a big deal since it's used as a clickable footer but the URL in https://ropensci.org/public_images/ropensci_footer.png is quite light? @karthik

**Comment by karthik** [comment]
Happy to bump the contrast on that. Not sure I have the original PSD file but I'll see about creating a new one.

**Comment by maelle** [comment]
Thank you!

**Comment by maelle** [comment]
See https://github.com/ropensci/software-review-meta/issues/79 (that said we still need to update the footer for the packages that already feature it, since it wouldn't be easy to remove it from all READMEs).

**Comment by maelle** [comment]
better in new design
