### ISSUE TITLE
Make sure the feeds for the commcalls and events pages are informative

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#454]
Or at least one of them i.e. either JSON or RSS.

**Comment by stefaniebutland** [comment]
from Curtis RStudio @maelle 
> if y'all ever add time to your https://ropensci.org/commcalls/index.json, we'd be able to include that in future events listings. (Right now the time listed in midnight.)

**Comment by maelle** [comment]
What about timezone, what format do they need time/timezone in?

**Comment by stefaniebutland** [comment]
asked Curtis for timezone deets

**Comment by stefaniebutland** [comment]
From Curtis:

> This actually the first webinar we've added to the events list. With Meetups (https://github.com/rladies/meetupr) we refer to the local time (where the meetup is held), but that's obviously complicated with a webinar.
> 
> At https://ropensci.org/commcalls/index.json, in the "date_published": "2019-05-07T00:00:00+00:00" field, I think the final 6 characters are used for timezone. +00:00 referring to GMT. Since y'all usually quote in pacific time, that'll vary between -7 and -8 depending on daylight savings.
> 
> You might have a look at how meetup handles this problem (details in the meetupr repo).

**Comment by maelle** [comment]
@stefaniebutland the "find your timezone" link template we have now works no matter the season, right?

**Comment by maelle** [comment]
Ah I found out why, that fantastic website uses location.

**Comment by maelle** [comment]
I am a bit stuck. @karthik Do you have any advice here? To get the time in GMT in the JSON feed of the comm calls page, we'd need to know what the comm call timezone is, and this varies by season as Curtis said, either PDT or PST.

Do we need to enter a special field with the time in GMT, i.e. when creating a comm call, writing the correct time in GMT? That sounds both repetitive and risky.

**Comment by maelle** [comment]
@stefaniebutland do we have any idea of the format RStudio calendar has? Could _they_ use some API to convert the Berkeley time, as long as they know it's a Berkeley time?

**Comment by maelle** [comment]
The meetupr repo doesn't help, the Meetup API itself seems to output both local and UTC time.

**Comment by stefaniebutland** [comment]
connected Curtis and Maëlle on Slack to resolve this directly
