### ISSUE TITLE
Make citations for ropensci software avail. somewhere on the site

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb2#505]
I manually collect citations via google scholar alerts, put them in this repo (https://github.com/ropenscilabs/ropensci_citations) in a csv file, then when a twitter bot run via heroku tweets a new citation, we commit back to the repo to citations_used.json file https://github.com/ropenscilabs/ropensci_citations/blob/master/citations_used.json

So we have citaitons in a machine readable json format. 

We should make this data available to the public.

- We could have a separate page on our site, or we could add it to an existing page
- Could pre-render or use JS to do client side
- Probably makes most sense to organize by package - but could have an option to sort/organize/filter by package maintainer, or even by other citation metadata (journal, year, etc., though we'd need to parse out that metadata [year, etc.] beforehand in the JSON file)
- We could link to an example image from a paper using the `img_path` key in the JSON, but i imagine we won't have room for that on the page
- We could link to papers, probably juse use the link to the landing page provided and not link to a pdf.
- note: If there is a DOI in the `doi` field, can construct url like 'https://doi.org/' + doi - If there is NOT a DOI, then the `citation` key will contain a url to the paper
  
any thoughts welcome

**Comment by stefaniebutland** [comment]
Can citations be displayed with most recent first please?

**Comment by maelle** [comment]
@stefaniebutland is this a request for Scott's JSON file or for https://roweb3-hugo.netlify.app/citations/?

I think we can close this issue since this is tackled in the website redesign.

**Comment by stefaniebutland** [comment]
closing is ok with me
