### ISSUE TITLE
Fix author page for Mauricio

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#522]
Mauricio's author page [`https://ropensci.org/authors/pacha/`](https://ropensci.org/authors/pacha/) does not link to his [blog post](https://ropensci.org/blog/2019/05/09/tradestatistics/). I'm not sure how to fix his [author file](https://github.com/ropensci/roweb2/blob/master/content/authors/pacha/_index.md) or post yaml. 

```
---
name: Pachá (aka Mauricio Vargas Sepúlveda)
link: https://pacha.hk/
twitter: pachamaltese
github: pachamaltese
---
```

```
---
slug: "tradestatistics"
title: Open Trade Statistics
package_version: 0.2.0
date: '2019-05-09'
authors:
  - Pachá (aka Mauricio Vargas Sepúlveda)
categories: blog
topicid: 1699
tags:
  - Software Peer Review
```

**Comment by maelle** [comment]
I can't remember _why_, but it turns out the folder name is important.

**Comment by maelle** [comment]
URL https://ropensci.org/authors/pach%C3%A1-aka-mauricio-vargas-sep%C3%BAlveda/
