### ISSUE TITLE
Add docs URL to packages table

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#535]
Cc @jeroen

**Comment by maelle** [comment]
Maybe simply replace the GitHub URL with the docs URL when it exists.

To know what docs websites exist one step should probably be added to the registry making cc @sckott.

**Comment by jeroen** [comment]
I think we should eventually be able to assume all packages in the registry have docs...

**Comment by maelle** [comment]
When is eventually? :slightly_smiling_face:

**Comment by jeroen** [comment]
I think we should be able to assume that now. We can check which of the packages still don't have docs.

```r
#install_github("jeroen/betty")
library(betty)
​
# List packages in registry
packages <- jsonlite::fromJSON("https://ropensci.github.io/roregistry/registry.json")$packages
packages$experimental <- grepl('github.com/ropenscilabs', packages$url)
​
# List docs.ropensci.org repos
docs <- betty:::get_docs_repos(active_only = TRUE)
packages$hasdocs <- packages$name %in% docs
​
# Find non-labs packages without docs
subset(packages, experimental == FALSE & hasdocs == FALSE)$name
```

We can try to fix remaining technical problems, or maybe some package can be removed from the registry.

```r
##  [1] "genbankr"          "treeio"            "bittrex"           "CoordinateCleaner" "fingertipsR"       "IEEER"            
##  [7] "jstor"             "MODIStsp"          "NLMR"              "phylotaR"          "plotdap"           "plotly"           
## [13] "rdflib"            "rdopa"             "restez"            "rrricanes"         "tabulizerjars"     "tacmagic"         
## [19] "virtuoso"          "weathercan"        "webmockr"  
```

For example `tabulizerjars` seems to be a support packages for `tabulizer`. It doesn't have any R functions and I don't think it has to be in the registry.
