### ISSUE TITLE
What should the default order of packages on the packages page be

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#537]
At the moment it seems... a bit random?

**Comment by maelle** [comment]
any opinion @jeroen @sckott, should we reorder the registry by alphabetical order or so? Or a random order every day? :-)

The current order is repos hosted in other orgs, then ropensci, then ropenscilabs.

**Comment by sckott** [comment]
maybe random? so that different pkgs get to be at the top?

**Comment by maelle** [comment]
fixed by #696
