### ISSUE TITLE
Make it clearer when packages have been peer reviewed

### ISSUE THREAD

**Issue by noamross** [ropensci/roweb2#542]
The table at https://ropensci.org/packages/ contains at least one package that is no longer part of rOpenSci e.g., `available` is now at `r-lib/available`.  I'm not sure how many others aren't there - I see that `rchie`, which was migrated out, is not in the table.

I also note it contains `ropenscilabs` packages without designating them as labs packages.  It would be helpful to do so, and also maybe make it clearer that the "dialogue" icon means "peer reviewed."

**Comment by maelle** [comment]
@sckott any idea why `available` is still in the registry? Thanks!

**Comment by sckott** [comment]
just removed available now, as well as icon. registry should be rebuilt on cron schedule in about an hour or so.

we don't have an automated thing for checking when repos leave our orgs, it doesn't happen very often so didn't build that in.

**Comment by maelle** [comment]
For discussion of keeping the list up to date see https://github.com/ropenscilabs/makeregistry/issues/16

@noamross you're also suggesting to make peer-reviewed status easier to see, do you have any particular idea of how this could look?

Reg labs packages I suppose this is linked to other discussions we have.

**Comment by noamross** [comment]
I think the current icon looks like "discuss this package," while a checkmark or something would be more appropriate.  But I think in any case it should be explicit with a column title of "peer-reviewed", or maybe the field should just contain all-text badges, e.g., `[CRAN] [PEER-REVIEWED] [STAFF MAINTAINED] [ARCHIVED]`.  

I'm working on the draft maintenance policy which I hope to get to everyone this week.

**Comment by maelle** [comment]
![image](https://user-images.githubusercontent.com/8360597/91286167-64c18d80-e78e-11ea-83bb-da8c5dac9ae0.png)

looks clearer in new design
