### ISSUE TITLE
Broken bits in treeio pkg blog post

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#543]
In treeio blog post,
- https://ropensci.org/blog/2018/05/17/treeio/
- https://raw.githubusercontent.com/ropensci/roweb2/master/content/blog/2018-05-17-treeio.md

Broken stuff
1. image does not display; no alt text in place of image `![](https://raw.githubusercontent.com/GuangchuangYu/treeio/master/vignettes/figures/codeml.png)`
1.  broken link https://bioconductor.org/packages/devel/bioc/vignettes/treeio/inst/doc/Importer.html
1. broken link https://bioconductor.org/packages/devel/bioc/vignettes/treeio/inst/doc/Exporter.html
1. broken link http://ginger.ucdavis.edu/r8s
1. links to treeio package should go to rOpenSci but I can't find the pkg in our org now https://github.com/ropensci?utf8=%E2%9C%93&q=treeio roregistry https://ropensci.github.io/roregistry/registry.json links to the book (https://yulab-smu.github.io/treedata-book/), not the code https://github.com/YuLab-SMU/treeio

**Comment by stefaniebutland** [comment]
re: 4) above, roregistry https://ropensci.github.io/roregistry/registry.json links to the book (https://yulab-smu.github.io/treedata-book/), not the code https://github.com/YuLab-SMU/treeio

**Comment by maelle** [comment]
Reg 1. the image doesn't exist so we might need to ask the author when we have solved 2, 3, 5 (in our docs building pipeline).

Reg 4. I'd suggest replacing the link with https://academic.oup.com/bioinformatics/article/19/2/301/372781

**Comment by maelle** [comment]
@GuangchuangYu there are a few broken links in your blog post, could you please make a PR to replace them?

Note that your package now has a pkgdown website up at https://docs.ropensci.org/treeio (cf  https://ropensci.org/technotes/2019/06/07/ropensci-docs/) that you can use to link the vignettes. 🙂

**Comment by GuangchuangYu** [comment]
I have problems in git clone the repo.

```
Cloning into 'roweb2'...
remote: Enumerating objects: 14352, done.
client_loop: send disconnect: Broken pipe00 KiB | 13.00 KiB/s
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

Can you kindly help me replace the links with the followings?

1. <https://yulab-smu.github.io/treedata-book/img/codeml.png>
2. <https://yulab-smu.github.io/treedata-book/chapter1.html>
3. <https://yulab-smu.github.io/treedata-book/chapter3.html>
4. <https://academic.oup.com/bioinformatics/article/19/2/301/372781> as recommended by @maelle

**Comment by maelle** [comment]
Ok I'll make the replacements, thanks a ton!

**Comment by maelle** [comment]
I also copy pasted the latest installation instructions from BIOC (i.e. not using bioclite.R).
