### ISSUE TITLE
Do we want blog post authors to add their Rmd source?

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#558]
If not can we gitignore Rmds?

cc @stefaniebutland

**Comment by maelle** [comment]
Ah :eyes: https://github.com/ropensci/roweb2/blob/bd38ab2e032f6a575bfab4c20d0feb2cfd1229af/.gitignore#L22

**Comment by stefaniebutland** [comment]
Question: does this mean the Rmd will NOT be kept when the post is merged, but WILL be present in the pull request I review?

**Comment by maelle** [comment]
Ah I think it's either all or nothing :thinking:

**Comment by stefaniebutland** [comment]
yep, workloopR Rmd was merged today.

**Comment by maelle** [comment]
We should also add this to the guidance ("add the Rmd to your PR so that Stef can make inline suggestions at the source" or so).

**Comment by maelle** [comment]
https://blogguide.ropensci.org/technical.html#make-a-pull-request
