### ISSUE TITLE
packages page filters styling

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb2#56]
Looks like this on my iphone 5S on both chrome and safari

![img_0736](https://user-images.githubusercontent.com/577668/31691442-fb6a4bbc-b34a-11e7-857f-1b8007734e6a.PNG)

Preview for mobile on my chrome browser makes it look pretty good on most mobile options, 

<img width="242" alt="screen shot 2017-10-17 at 2 54 46 pm" src="https://user-images.githubusercontent.com/577668/31691494-2650a8f8-b34b-11e7-9eaa-58fb818b3931.png">

but I don't get that nice view unfortunately IRL

**Comment by maelle** [comment]
@sckott still the case?

**Comment by sckott** [comment]
yes, still the same

**Comment by maelle** [comment]
any idea what could cause this? @jeroen?

**Comment by maelle** [comment]
@sckott does it also look ugly in https://deploy-preview-308--ropensci.netlify.com/packages/ ? JS libraries were updated, so who knows.

**Comment by sckott** [comment]
still bad

**Comment by maelle** [comment]
😢🤔

**Comment by marulango** [comment]
Oh my! Just saw this, will give it a look later tonight.

**Comment by maelle** [comment]
cf #330 thanks @marulango
