### ISSUE TITLE
Why does this file sit on our root?

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb2#567]
https://github.com/ropensci/roweb2/blob/master/author-name.md

Any idea @stefaniebutland 
Was this from a blog post? Can we delete it?

**Comment by stefaniebutland** [comment]
Maëlle created it as template for an author file

Linked to from https://github.com/ropensci/roweb2#create-an-authors-index-file-for-yourself-author-file

**Comment by karthik** [comment]
ok thanks. Seems like an odd place for it but I'm guessing she had good reason for it @maelle

**Comment by maelle** [comment]
Not at all and I can move it to roblog.

**Comment by maelle** [comment]
Ok so now the template is in roblog https://github.com/ropenscilabs/roblog#author-file (whose docs will be improved as @stefaniebutland and I collaborate on the guidance).
