### ISSUE TITLE
Comm call disappeared from Upcoming Events too early

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#572]
On 2019-12-05, event https://ropensci.org/commcalls/2019-12-05/ no longer appeared on https://ropensci.org/events/ page

Maëlle I think you fixed it before to disappear the day after the event.

**Comment by maelle** [comment]
I can't reproduce the bug locally.

@karthik I'd need two pieces of info from you please :-)
* at what time is the daily website build triggered?
* what's the timezone for that build?

**Comment by maelle** [comment]
I am guessing 9:10AM my time :thinking:
