### ISSUE TITLE
Broken image in blog post

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#585]
In https://ropensci.org/blog/2013/06/19/usgs-app/

![Screen Shot 2019-12-18 at 3 15 34 PM](https://user-images.githubusercontent.com/11927811/71131320-3f18c900-21a9-11ea-8aef-e6c63de74ab3.png)

**Comment by maelle** [comment]
Right. Is the app still online @sckott ? Maybe I should use internet archive.

**Comment by sckott** [comment]
woah, throw back wednesdays, seems like so long ago

i don't know, i'll have a look tomorrow and see if I can at least get it running

the image is here in roweb repo https://github.com/ropensci/roweb/blob/master/assets/blog-images/usgsapp.png

**Comment by maelle** [comment]
Actually here it was already Thursday so very fitting for a throw back Thursday :stuck_out_tongue_winking_eye: 

Thanks, I'll assign this to you.

Thanks @stefaniebutland for catching it.

**Comment by maelle** [comment]
It doesn't seem fixed, did my PR at the time mess things up?

**Comment by sckott** [comment]
was in a PR that we didn't merge, should be fixed now

**Comment by maelle** [comment]
Thank you!
