### ISSUE TITLE
Add an alert to the oldest posts?

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#586]
I like the alert banner on https://kb.iu.edu/d/abwp

**Comment by maelle** [comment]
cc @stefaniebutland

**Comment by stefaniebutland** [comment]
I like the banner too.
Would we need to say it's "archived"? or just say the content is no longer maintained.

**Comment by maelle** [comment]
Yes, the "archived" word is probably not optimal for the blog.

We'd need to define what's "old".

Technically, 

* it could be handled by adding a preface YAML field to the corresponding R Markdown (added automatically with an R script run once in a while) like what you do in https://github.com/ropensci/roweb2/blob/master/content/blog/2019-10-17-news-oct2019.md

* Or, by Hugo, depending on the date of the page (for the blog and tech notes only) compared to "now" i.e. a conditional thing like we do for events (but it'd be something like "if now - date > 2 years then add banner else don't").

A reader can see the date and guess it's a bit old, so maybe adding a banner is over the top.

**Comment by stefaniebutland** [comment]
I'm leaning toward not automatically adding a banner. Some posts will age much better than others so a setting by date of post would make some good posts look not so good

If a post was really outdated we could manually add a preface
