### ISSUE TITLE
Is `twitterImg` in blog post YAML working?

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#591]
In this [blog post](https://raw.githubusercontent.com/ropensci/roweb2/master/content/blog/2019-12-20-news-dec2019.md) I used `twitterImg: img/blog-images/2019-12-20-news-dec2019/2months2mins_hex.png` but in [twitter card validator](https://cards-dev.twitter.com/validator), preview of image does not show.

Is it me?

**Comment by maelle** [comment]
What is the preview link?

**Comment by stefaniebutland** [comment]
published https://ropensci.org/blog/2019/12/20/news-dec2019/

**Comment by maelle** [comment]
Fixed it.

I'm a bit annoyed because it doesn't work in previews where the baseURL doesn't end with a slash, whereas in the production environment the baseURL (set in the config of our site) ends with a slash. Oh, well, not too bad.
