### ISSUE TITLE
Blog instructions in README

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#610]
@stefaniebutland should we fix the template stuff there OR replace the whole section with a link to the guidance?

**Comment by maelle** [comment]
I'd be in favor of replacing the whole section but that'd be a soft launch.

**Comment by maelle** [comment]
I now see, sorry, it was the RStudio menu thing.

@stefaniebutland cf https://github.com/ropensci/roweb2/issues/610

**Comment by stefaniebutland** [comment]
What do you mean by "the RStudio menu thing". #610 is this issue so not sure

**Comment by maelle** [comment]
Sorry I meant to post in the roblog issue.
