### ISSUE TITLE
In future redesign, add icon to edit posts?

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#634]
I.e. when reading a blog post, add a direct link to its Markdown/RMarkdown source?

It'd be useful for folks who want to fix a typo, and future authors who want to compare the rendered version with the source.

See e.g. the button on my blog posts https://masalmon.eu/2020/02/29/hugo-maintenance/

cc @stefaniebutland

**Comment by stefaniebutland** [comment]
I LOVE that

**Comment by maelle** [comment]
cc @karthik -- we'd probably need an icon that looks discrete+elegant, with a title that makes it clear what it does on hovering ("View/amend page source").

**Comment by karthik** [comment]
OK I have asked him to work on this.

**Comment by maelle** [comment]
closing this here since it's tackled there. thanks!
