### ISSUE TITLE
discourse embed is too narrow

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb2#639]
@maelle looks like the discourse embed for at least this post that just got a discussion item is too narrow 

<img width="875" alt="Screen Shot 2020-03-09 at 3 05 39 PM" src="https://user-images.githubusercontent.com/577668/76261569-88603e00-6217-11ea-87c9-e05303b1b5c4.png">

vs. what I think looks better/correct

<img width="851" alt="Screen Shot 2020-03-09 at 3 10 29 PM" src="https://user-images.githubusercontent.com/577668/76261882-3bc93280-6218-11ea-9ae1-b753a8c3c04c.png">

where the forum embed is the same width as the blog post text body

**Comment by maelle** [comment]
Ok so it's tech notes vs blog/comm calls, I'll look into this.

**Comment by maelle** [comment]
@sckott if you look at the embed thing via Chrome/Firefox devtools you'll see it's a full html page within the page, with a head. Is this needed? Can this be tweaked somehow?

**Comment by sckott** [comment]
thanks!
