### ISSUE TITLE
Slides link not showing in comm call resources list

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#649]
This

```
resources:
  - url: https://speakerdeck.com/juliasilge/maintaining-an-r-package
    name: Julia Silge's presentation slides
```

in https://github.com/ropensci/roweb2/blob/master/content/commcalls/2020-03-18.md

is not rendered in https://ropensci.org/commcalls/2020-03-18/

Can't figure out what's wrong

**Comment by maelle** [comment]
Nothing was wrong in the source, Netlify had a system error. I've made a commit to force a deploy and all is well now.
