### ISSUE TITLE
Add an output hook to Rmd template

### ISSUE THREAD

**Issue by maelle** [ropensci/roweb2#653]
To support https://gohugo.io/content-management/syntax-highlighting/#highlighting-in-code-fences (especially highlighting lines 😍)

Ouput hook cf https://bookdown.org/yihui/rmarkdown-cookbook/hook-hide.html

The setup chunk is getting long, maybe the plot and output hooks should be exported functions of a hugormd package. Pro: shorter setup chunk, tests. Con: users need to install a package. The con wins at the moment.

**Comment by stefaniebutland** [comment]
> Con: users need to install a package. 

seems like a big con to me

**Comment by maelle** [comment]
Yeah, and your idea to add a comment before the plot hook can be applied to this hook to make it less weird, so I'll just add a few lines to the Rmd template. 

I'm sure I'll find many opportunities to use line highlighting in the future :grin:

**Comment by maelle** [comment]
Examples https://deploy-preview-651--ropensci.netlify.com/blog/2020/04/05/syntax-highlighting/

The PR #651 amends the archetype, adding a comment before the existing options and hook, and adding a source hook.
