### ISSUE TITLE
Redirect to custom docs urls if they exist or are being used?

### ISSUE THREAD

**Issue by jonkeane** [ropensci/roweb2#716]
I recently finished the onboarding for [dittodb](https://github.com/ropensci/dittodb/), and I'm hosting my own docs outside of rOpenSci's docs (there are a few different reasons for this that I can explain in more detail, but don't want to distract). From what I'm seeing the rOpenSci docs are still generated automatically and are linked to from [the packages](https://ropensci.org/packages/) page. 

I was wondering if there would be openness to accepting a PR to the appropriate repos that would let the documentation links go to that custom URL? 

I could think of two ways of doing this, though I'm sure there are many more:
* Edit the roregistry parsing to have a custom docs field (only triggered by a file in the package repo (e.g. in ropensci/dittodb)? a manual override?)  and then use that in [tableinit.js](https://github.com/ropensci/roweb2/blob/master/themes/ropensci/static/js/tableinit.js#L22)
* Add a switch to ropensci/docs that would make an html file with a meta refresh redirect (e.g. `<meta http-equiv="refresh" content="0; URL=custom_url.com" />`) (again, triggered by a file in the repo?)

I'm very happy to work on such PR(s), but wanted to make an issue first to make sure that there wasn't opposition to the idea.

**Comment by maelle** [comment]
:wave: @jonkeane! Thanks for taking the time to explore things. However we're against such special rules for a few reasons.

* It'd mean adding complexity to the registry and docs building pipelines that are already quite complex.

* If your custom domain website disappears, we wouldn't know whereas the docs building pipeline shows docs status. It [happened to e.g. rtweet.info](https://twitter.com/steffenlinguist/status/1282966029476536320).

* The docs websites share colours but also a footer with our website.

Now, you can keep listing your own URL in DESCRIPTION and in the repo URL as you do know!

To re-direct more traffic to your own websites, by the way, I'd advise adding an author field, I made a PR to your repo. https://github.com/ropensci/dittodb/pull/124

**Comment by maelle** [comment]
For info, I've just checked that [downlit's autolinking](https://github.com/r-lib/downlit#cross-package-links) (used in pkgdown and hugodown) gives priority to your website cc @jeroen (the rOpenSci docs [special case](https://github.com/r-lib/downlit/blob/7677e40628308380706f7025c672d76eb8970689/R/metadata.R#L89) doesn't take precedence over your custom domain)

``` r
downlit::autolink("library(dittodb)")
#> [1] "<a href='https://dittodb.jonkeane.com'>library(dittodb)</a>"
```

<sup>Created on 2020-07-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jonkeane** [comment]
Thanks for all the information and the PR!
