### ISSUE TITLE
No packages displayed on https://ropensci.org/packages/

### ISSUE THREAD

**Issue by mskyttner** [ropensci/roweb2#725]
I was looking for bibliometrics related packages from ROpenSci and tried w latest firefox and chromium to get the web page at https://ropensci.org/packages/ but it seems that the list of packages does not display. I guess the table is supposed to display when the page has loaded, since I didn't find any "Search" button? I checked with my desktop machine and Android phone. 

I can get the list with curl/httpie using `http ropensci.github.io/roregistry/registry.json` so it might be an issue with the data.table not loading and displaying on the web page?

**Comment by maelle** [comment]
@mskyttner yes my fault I broke the status string in the JSON so you'll have to uncheck the active repos box. it should be fixed soon, sorry!!

Now you might prefer looking at packages on the new website (to be launched soon) https://roweb3-hugo.netlify.app/packages/all/ (feedback welcome!)

**Comment by mskyttner** [comment]
No worries, just sending this in case others were running into it, for my own part I found what I needed (refsplitr, europepmc) through the JSON file with:

```r
library(jsonlite)
library(dplyr)
library(DT)

tbl <- 
  jsonlite::fromJSON("https://ropensci.github.io/roregistry/registry.json")$packages %>%
  dplyr::as_tibble() 

# the full table
tbl %>% DT::datatable()

# package w descriptions/details containing word "metric"
tbl %>% 
  dplyr::filter(grepl(".*?metric.*?", paste(details, description))) %>%
  dplyr::pull(name)
```

**Comment by maelle** [comment]
cool! I hope search in the website itself will be nice to use but in some cases exploring the data locally might help indeed.

If you end up using the packages you found and have time, you can report your use case at https://discuss.ropensci.org/c/usecases/10 btw :-)
