### ISSUE TITLE
Event attendees not visible on Events page

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#728]
Sorry for an roweb2 issue Maëlle. 

This event looks ok: https://ropensci.org/events/2020-10-22-rladies-eastlansing/, but [Events page](https://ropensci.org/events/) does not list Brooke and me.

[source](https://github.com/ropensci/roweb2/blob/master/content/events/2020-10-22-rladies-eastlansing.md)

**Comment by maelle** [comment]
How to motivate me even more for launching the new design: making me see how maintaining two will be difficult :joy:
