### ISSUE TITLE
what belongs on Use Cases page?

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#73]
I see that [Use Cases](https://new.ropensci.org/usecases/) page says "examples on our most popular packages"

Do our > 10 blog posts on onboarded software count as use cases and should we add them? (they're not necessarily most popular pkgs)

Is this a place we could list citations of our packages e.g. those that @sckott collects for rOpenSci News e.g. https://ropensci.github.io/biweekly/update-2017-10-09/? Sets a great example showing people it's cool to cite software.

**Comment by sckott** [comment]
> Have a link to the raw data of all citations? Later it could be a searchable table by package/topic? (and could be fed to the packages docs as well)

Agree to link to citation data. 

> Would there be a way to digest the newsletter previous issues for that, just to have a direct link that'd be the blurbs from the newsletter? I guess it's also fine to have a link to previous issues in general to start with, not the use cases section. cf #187

Agree to link to newsletter. Not sure the best way to use newsletter use case things on a new use cases page on our site. we probably don't want to overwhelm a user on the page. Maybe they could be grouped by package, and then only shown when you select a package or so?

> There could also be a link to the new Twitter account.

Agree

> Not sure how to link the tweets Scott's has been writing as reactions to the bot's tweets e.g.

Hmm, I don't think I will keep doing those tweets for every one :)

**Comment by maelle** [comment]
> Maybe they could be grouped by package, and then only shown when you select a package or so? 

We might need more structured metadata about packages then, keeping track of where they've been blogged about + in which papers they've been used.

But as a summary easier things mentioned in this thread are adding a link to the Twitter account, to the raw citation data and to the newsletter to the use cases page. 

Maybe there could also be a blurb indicating how use cases are currently found, and how to report them (like https://ropensci.github.io/dev_guide/contributingguide.html#reporting-use-cases )

**Comment by sckott** [comment]
well, we can include how to report, but i think i've maybe had 1 or 2 instances where someone's reported a use case, it's almost entirely our job to do so i think :/

**Comment by maelle** [comment]
Proposed workflow (not to be implemented now, just writing it here for not forgetting about it).

Semi-automatically convert use cases from the forum + maybe a few from the old html use cases #299 to some sort of Markdown/YAML format under content/usecases (with author, package, title, link, code, image etc. as fields -- leaf bundles to make images easier to store).
