### ISSUE TITLE
blog posts to fix

### ISSUE THREAD

**Issue by sckott** [ropensci/roweb2#83]
- http://localhost:1313/blog/2016/11/22/geospatial-suite/ fix colored labels
- http://localhost:1313/blog/2016/03/17/ropensci-geospatial-stack/ same as above
- footnotes in http://localhost:1313/blog/2015/06/03/baad/ not linking to anchors
- ...

**Comment by maelle** [comment]
@sckott can I help? Are there other posts than the ones linked here that you thought of when writing "..."? Maybe I should "simply" use html-proofer.

**Comment by sckott** [comment]
there are probably other ones. a tool to find problems would be good

**Comment by maelle** [comment]
I'd like to close that issue once you @sckott are happy for these 3 blog posts. We can fix others as we find them, and html checking is the topic of another issue, #190.
