### ISSUE TITLE
post-launch add people to About page

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#84]
On About page
- [ ] add Researchers section under Team. Include Dan Sholler, Nick Golding, new Fellows
- [ ] add Dan Katz to Collaborators
- [ ] add or subtract people to Collaborators based on criteria: "Our collaborators include Associate Editors of our open peer review system, people whose packages have been reviewed and onboarded to rOpenSci, reviewers of two or more packages, and others who have contributed significant time and effort to rOpenSci."

**Comment by stefaniebutland** [comment]
@jeroen Karthik suggested I ask for your help to get this done (i.e. can you please do it when you have time?)
It's super important we get Dan Sholler up and Nick Golding. Karthik suggested a Researchers section under Team, using same format as Team

**Meet our Researchers**
picture (roweb/assets/blog-images/2017-06-30-postdoc-dan-sholler/dan-sholler.jpg)
Dan Sholler
Postdoc (= new badge?)

picture (roweb/assets/blog-images/2016-12-12-ropensci-fellowship-zoon/nick-golding.jpg)
Nick Golding
Fellow (= new badge?)

2-3 new Fellows likely added before end of 2017.

**Comment by stefaniebutland** [comment]
@jeroen ...but I have an additional greedy proposal for listing people that I think is important but @karthik and @sckott should weigh in on before making changes

**Meet our Team**
I propose adding onboarding editors here and listing people in this order:
- staff
- editor = new badge; copy Maelle and Noam up here; add badge to Karthik and Scott
- leadership
- advisor
- alumnus

**Meet our Researchers**
as proposed above

**Meet our Collaborators**
- add Dan Katz here
- keep Noam and Maelle here as they contribute more than just as editors

**Comment by stefaniebutland** [comment]
@jeroen Karthik and I are discussing this on another channel rn

**Comment by maelle** [comment]
I agree about adding fellows and non-onboarding collaborators. Is there already somewhere a list of people who contributed significant time and effort to rOpenSci, e.g. people who sat on committees? E.g. for the fellowships the committee was mentioned [in blog posts](https://ropensci.org/blog/2018/02/14/announcing-2018-ropensci-fellows/).

Reg onboarding I think editors should be added to the about page even if in the future we plan to have an onboarding landing page cf #213 Reviewers are listed in the onboarding README and in https://ropensci.github.io/dev_guide/onboardingintro.html#reviewers but currently _maintainers_ of rOpenSci packages, onboarded or not, are not listed anywhere yet. Then one could debate adding _authors_, not only _maintainers_, of packages, and later also _contributors_. Maybe a link to some raw list extracted from the Codemeta data when it's deployed.

The discussion is linked to #110 too.

I wonder how much work it'd be to add URLs when mentioning people (for package maintainers, it can simply be their GitHub account).

**Comment by sckott** [comment]
> is there already somewhere a list of people who contributed significant time and effort to rOpenSci, e.g. people who sat on committees?

not that I know of

yeah, could use url to github user if code related

**Comment by stefaniebutland** [comment]
related issue for this discussion: #120
