### ISSUE TITLE
improve calendar content

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/roweb2#92]
Upcoming events here https://new.ropensci.org/
- how do I add link to an event website
- how do I format event happening on a single day rather than span

**Comment by maelle** [comment]
At the moment there are 3 issues linked to the calendar #157 #155 #92, I've just added a label for easier browsing.

**Comment by stefaniebutland** [comment]
Underlying calendar issue is that it really should be re-done from the ground up, including consideration of where it should appear on our site for visibility/linkability

My current work-not-flow is:
- add an event to public rOpenSci Google cal
- add same item here: https://github.com/ropensci/roweb2/blob/master/themes/ropensci/static/js/calendarJSON.js to appear on our website calendar on /home and /community
- once a week, delete past events from https://github.com/ropensci/roweb2/blob/master/themes/ropensci/static/js/calendarJSON.js
- every couple of months, put calendar content in blog post (into table with different content) e.g. https://ropensci.org/blog/2018/06/19/ropensci-at-meetings/
- ~ once a month, tweet events rOpenSci ppl are at

**Comment by maelle** [comment]
would you want to embed the Google cal?

Thought of this because I saw https://github.com/lockedatapublished/hugo-utilitybelt/blob/master/layouts/shortcodes/fullcalendar_gcal.html

**Comment by stefaniebutland** [comment]
Yes I think it's ideal to embed the Google cal as long as people are ok with the aesthetics.

**Comment by maelle** [comment]
I could try it in a branch some day and see whether we can still use rOpenSci style on it.

It'd solve steps 2 and 3 of your worknotflow.

**Comment by maelle** [comment]
cf #358
