### ISSUE TITLE
Use custom RSS feed template

### ISSUE THREAD

**Issue by karthik** [ropensci/roweb2#98]
I see Hugo supports it: https://gohugo.io/templates/rss/

We'll need one for blog/technotes

**Comment by jeroen** [comment]
Yes we should change the rss template so that the full content is included. This is important for aggregators that mirror the content, e.g. r-bloggers.

**Comment by jeroen** [comment]
Fixed via https://github.com/ropensci/roweb2/commit/0a20f71790e01600844224ed18193afa2a5e3918
